// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api/proto/scraper/scraper.proto

/*
Package scraper is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package scraper

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_ScrapeService_CreateScrapeLiveEventsJob_0(ctx context.Context, marshaler runtime.Marshaler, client ScrapeServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateScrapeLiveEventsJobRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateScrapeLiveEventsJob(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ScrapeService_CreateScrapeLiveEventsJob_0(ctx context.Context, marshaler runtime.Marshaler, server ScrapeServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreateScrapeLiveEventsJobRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateScrapeLiveEventsJob(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterScrapeServiceHandlerServer registers the http handlers for service ScrapeService to "mux".
// UnaryRPC     :call ScrapeServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterScrapeServiceHandlerFromEndpoint instead.
func RegisterScrapeServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ScrapeServiceServer) error {

	mux.Handle("POST", pattern_ScrapeService_CreateScrapeLiveEventsJob_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/neptuneg.go_back.serivces.scraper.ScrapeService/CreateScrapeLiveEventsJob", runtime.WithHTTPPathPattern("/v1/scraper/live_event_jobs"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ScrapeService_CreateScrapeLiveEventsJob_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScrapeService_CreateScrapeLiveEventsJob_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterScrapeServiceHandlerFromEndpoint is same as RegisterScrapeServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterScrapeServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterScrapeServiceHandler(ctx, mux, conn)
}

// RegisterScrapeServiceHandler registers the http handlers for service ScrapeService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterScrapeServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterScrapeServiceHandlerClient(ctx, mux, NewScrapeServiceClient(conn))
}

// RegisterScrapeServiceHandlerClient registers the http handlers for service ScrapeService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ScrapeServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ScrapeServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ScrapeServiceClient" to call the correct interceptors.
func RegisterScrapeServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ScrapeServiceClient) error {

	mux.Handle("POST", pattern_ScrapeService_CreateScrapeLiveEventsJob_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/neptuneg.go_back.serivces.scraper.ScrapeService/CreateScrapeLiveEventsJob", runtime.WithHTTPPathPattern("/v1/scraper/live_event_jobs"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ScrapeService_CreateScrapeLiveEventsJob_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScrapeService_CreateScrapeLiveEventsJob_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_ScrapeService_CreateScrapeLiveEventsJob_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "scraper", "live_event_jobs"}, ""))
)

var (
	forward_ScrapeService_CreateScrapeLiveEventsJob_0 = runtime.ForwardResponseMessage
)
