// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/proto/scraper/scraper.proto

package scraper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScrapeLiveEventsJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveHouseSlug string `protobuf:"bytes,1,opt,name=live_house_slug,json=liveHouseSlug,proto3" json:"live_house_slug,omitempty"`
	YearMonth     string `protobuf:"bytes,2,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`
}

func (x *CreateScrapeLiveEventsJobRequest) Reset() {
	*x = CreateScrapeLiveEventsJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_scraper_scraper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScrapeLiveEventsJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScrapeLiveEventsJobRequest) ProtoMessage() {}

func (x *CreateScrapeLiveEventsJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scraper_scraper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScrapeLiveEventsJobRequest.ProtoReflect.Descriptor instead.
func (*CreateScrapeLiveEventsJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scraper_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScrapeLiveEventsJobRequest) GetLiveHouseSlug() string {
	if x != nil {
		return x.LiveHouseSlug
	}
	return ""
}

func (x *CreateScrapeLiveEventsJobRequest) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

type CreateScrapeLiveEventsJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *CreateScrapeLiveEventsJobResponse) Reset() {
	*x = CreateScrapeLiveEventsJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_scraper_scraper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScrapeLiveEventsJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScrapeLiveEventsJobResponse) ProtoMessage() {}

func (x *CreateScrapeLiveEventsJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scraper_scraper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScrapeLiveEventsJobResponse.ProtoReflect.Descriptor instead.
func (*CreateScrapeLiveEventsJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scraper_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScrapeLiveEventsJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_api_proto_scraper_scraper_proto protoreflect.FileDescriptor

var file_api_proto_scraper_scraper_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x72, 0x61,
	0x70, 0x65, 0x72, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x22, 0x69, 0x0a, 0x20, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x69, 0x76, 0x65,
	0x5f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6c, 0x69, 0x76, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x53, 0x6c, 0x75, 0x67,
	0x12, 0x1d, 0x0a, 0x0a, 0x79, 0x65, 0x61, 0x72, 0x5f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x79, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x22,
	0x3a, 0x0a, 0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x4c,
	0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x32, 0x98, 0x01, 0x0a, 0x0d,
	0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x86, 0x01,
	0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x4c, 0x69,
	0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4a, 0x6f, 0x62, 0x12, 0x33, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x72, 0x61, 0x70,
	0x65, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x65, 0x70, 0x74, 0x75, 0x6e, 0x65, 0x47, 0x2f, 0x67, 0x6f,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_scraper_scraper_proto_rawDescOnce sync.Once
	file_api_proto_scraper_scraper_proto_rawDescData = file_api_proto_scraper_scraper_proto_rawDesc
)

func file_api_proto_scraper_scraper_proto_rawDescGZIP() []byte {
	file_api_proto_scraper_scraper_proto_rawDescOnce.Do(func() {
		file_api_proto_scraper_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_scraper_scraper_proto_rawDescData)
	})
	return file_api_proto_scraper_scraper_proto_rawDescData
}

var file_api_proto_scraper_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_scraper_scraper_proto_goTypes = []interface{}{
	(*CreateScrapeLiveEventsJobRequest)(nil),  // 0: api.proto.scraper.CreateScrapeLiveEventsJobRequest
	(*CreateScrapeLiveEventsJobResponse)(nil), // 1: api.proto.scraper.CreateScrapeLiveEventsJobResponse
}
var file_api_proto_scraper_scraper_proto_depIdxs = []int32{
	0, // 0: api.proto.scraper.ScrapeService.CreateScrapeLiveEventsJob:input_type -> api.proto.scraper.CreateScrapeLiveEventsJobRequest
	1, // 1: api.proto.scraper.ScrapeService.CreateScrapeLiveEventsJob:output_type -> api.proto.scraper.CreateScrapeLiveEventsJobResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_scraper_scraper_proto_init() }
func file_api_proto_scraper_scraper_proto_init() {
	if File_api_proto_scraper_scraper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_scraper_scraper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScrapeLiveEventsJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_scraper_scraper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScrapeLiveEventsJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_scraper_scraper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_scraper_scraper_proto_goTypes,
		DependencyIndexes: file_api_proto_scraper_scraper_proto_depIdxs,
		MessageInfos:      file_api_proto_scraper_scraper_proto_msgTypes,
	}.Build()
	File_api_proto_scraper_scraper_proto = out.File
	file_api_proto_scraper_scraper_proto_rawDesc = nil
	file_api_proto_scraper_scraper_proto_goTypes = nil
	file_api_proto_scraper_scraper_proto_depIdxs = nil
}
