version: "3.9"

services:
  app:
    container_name: go-back-app
    build:
      context: ./app
      target: dev
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: go-back-db
    image: postgres:14.1-alpine3.14
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: dev
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    container_name: go-back-redis
    image: redis:6.2.6-alpine3.14
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  sidekiq:
    container_name: go-back-sidekiq
    build:
      context: ./sidekiq
    depends_on:
      - redis
    volumes:
      - ./sidekiq:/app

volumes:
  data:
  redis:
