// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: api/proto/payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreateLiveEventOrder(ctx context.Context, in *CreateLiveEventOrderRequest, opts ...grpc.CallOption) (*CreateLiveEventOrderResponse, error)
	CreateUserPoints(ctx context.Context, in *CreateUserPointsRequest, opts ...grpc.CallOption) (*CreateUserPointsResponse, error)
	GetUserPoints(ctx context.Context, in *GetUserPointsRequest, opts ...grpc.CallOption) (*GetUserPointsResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateLiveEventOrder(ctx context.Context, in *CreateLiveEventOrderRequest, opts ...grpc.CallOption) (*CreateLiveEventOrderResponse, error) {
	out := new(CreateLiveEventOrderResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.PaymentService/CreateLiveEventOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateUserPoints(ctx context.Context, in *CreateUserPointsRequest, opts ...grpc.CallOption) (*CreateUserPointsResponse, error) {
	out := new(CreateUserPointsResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.PaymentService/CreateUserPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetUserPoints(ctx context.Context, in *GetUserPointsRequest, opts ...grpc.CallOption) (*GetUserPointsResponse, error) {
	out := new(GetUserPointsResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.PaymentService/GetUserPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	CreateLiveEventOrder(context.Context, *CreateLiveEventOrderRequest) (*CreateLiveEventOrderResponse, error)
	CreateUserPoints(context.Context, *CreateUserPointsRequest) (*CreateUserPointsResponse, error)
	GetUserPoints(context.Context, *GetUserPointsRequest) (*GetUserPointsResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) CreateLiveEventOrder(context.Context, *CreateLiveEventOrderRequest) (*CreateLiveEventOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLiveEventOrder not implemented")
}
func (UnimplementedPaymentServiceServer) CreateUserPoints(context.Context, *CreateUserPointsRequest) (*CreateUserPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserPoints not implemented")
}
func (UnimplementedPaymentServiceServer) GetUserPoints(context.Context, *GetUserPointsRequest) (*GetUserPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPoints not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateLiveEventOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLiveEventOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateLiveEventOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.PaymentService/CreateLiveEventOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateLiveEventOrder(ctx, req.(*CreateLiveEventOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.PaymentService/CreateUserPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateUserPoints(ctx, req.(*CreateUserPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.PaymentService/GetUserPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetUserPoints(ctx, req.(*GetUserPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLiveEventOrder",
			Handler:    _PaymentService_CreateLiveEventOrder_Handler,
		},
		{
			MethodName: "CreateUserPoints",
			Handler:    _PaymentService_CreateUserPoints_Handler,
		},
		{
			MethodName: "GetUserPoints",
			Handler:    _PaymentService_GetUserPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/payment/payment.proto",
}
