# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

gem 'faktory_worker_ruby'
gem 'metainspector', '~> 5.11'
gem 'parallel', '~> 1.20'
gem 'redis', '~> 4.0'
gem 'webrick', '~> 1.7'
gem 'yabeda'
gem 'yabeda-faktory'
gem 'yabeda-prometheus'
