name: 'Build And Push Image'
description: 'Builds and pushes an image with a tag of the commit SHA'
inputs:
  dockerfile:
    description: 'Dockerfile to build'
    required: true
  context:
    description: 'Context to build'
    required: true
  tags:
    description: 'Tags to push'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.tags }}
