// Code generated by sqlc. DO NOT EDIT.
// source: user_points.sql

package db

import (
	"context"

	"github.com/NeptuneG/go-back/pkg/db/types"
	"github.com/google/uuid"
)

const createUserPoints = `-- name: CreateUserPoints :one
INSERT INTO user_points (
  user_id, points, description, order_type, order_id, tx_id
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, points, description, order_type, order_id, created_at, updated_at, tx_id
`

type CreateUserPointsParams struct {
	UserID      uuid.UUID        `json:"user_id"`
	Points      int32            `json:"points"`
	Description types.NullString `json:"description"`
	OrderType   string           `json:"order_type"`
	OrderID     uuid.UUID        `json:"order_id"`
	TxID        types.NullString `json:"tx_id"`
}

func (q *Queries) CreateUserPoints(ctx context.Context, arg CreateUserPointsParams) (UserPoint, error) {
	row := q.queryRow(ctx, q.createUserPointsStmt, createUserPoints,
		arg.UserID,
		arg.Points,
		arg.Description,
		arg.OrderType,
		arg.OrderID,
		arg.TxID,
	)
	var i UserPoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Points,
		&i.Description,
		&i.OrderType,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TxID,
	)
	return i, err
}

const deleteUserPointsByTxID = `-- name: DeleteUserPointsByTxID :exec
DELETE FROM user_points WHERE tx_id = $1
`

func (q *Queries) DeleteUserPointsByTxID(ctx context.Context, txID types.NullString) error {
	_, err := q.exec(ctx, q.deleteUserPointsByTxIDStmt, deleteUserPointsByTxID, txID)
	return err
}

const getUserPoints = `-- name: GetUserPoints :one
SELECT COALESCE(SUM(points), 0) FROM user_points WHERE user_id = $1
`

func (q *Queries) GetUserPoints(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.queryRow(ctx, q.getUserPointsStmt, getUserPoints, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
