// Code generated by sqlc. DO NOT EDIT.
// source: user_orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserOrder = `-- name: CreateUserOrder :one
INSERT INTO user_orders (
  user_id, live_event_id
) VALUES (
  $1, $2
) RETURNING id, live_event_id, user_id, created_at, updated_at
`

type CreateUserOrderParams struct {
	UserID      uuid.UUID `json:"user_id"`
	LiveEventID uuid.UUID `json:"live_event_id"`
}

func (q *Queries) CreateUserOrder(ctx context.Context, arg CreateUserOrderParams) (UserOrder, error) {
	row := q.queryRow(ctx, q.createUserOrderStmt, createUserOrder, arg.UserID, arg.LiveEventID)
	var i UserOrder
	err := row.Scan(
		&i.ID,
		&i.LiveEventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
