name: Build and Push Live Image
on:
  push:
    branches:
      - main
    paths:
    - 'internal/live/**'
    - 'cmd/live/**'
    - 'api/proto/live/**'
    - 'build/docker/live/**'

jobs:
  push_to_registry:
    name: Push live-service image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/live/Dockerfile
          context: .
          tags: quay.io/goss_beta/live-service:${{ github.sha }}
