name: Build and Push Faktory-workers Image
on:
  push:
    branches:
      - main
    paths:
    - 'cmd/faktory-workers/**'
    - 'build/docker/faktory-workers/**'

jobs:
  push_to_registry:
    name: Push faktory-workers image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/faktory-workers/Dockerfile
          context: cmd/faktory-workers
          tags: quay.io/goss_beta/faktory-workers:${{ github.sha }}
