name: Build and Push Scraper Image
on:
  push:
    branches:
      - main
    paths:
    - 'internal/scraper/**'
    - 'cmd/scraper/**'
    - 'api/proto/scraper/**'
    - 'build/docker/scraper/**'

jobs:
  push_to_registry:
    name: Push scraper-service image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/scraper/Dockerfile
          context: .
          tags: quay.io/goss_beta/scraper-service:${{ github.sha }}
