name: Build and Push Faktory-workers Image
on:
  push:
    branches:
      - main
    paths:
    - 'cmd/faktory-workers/**'
    - 'build/docker/faktory-workers/**'

jobs:
  push_to_registry:
    name: Push faktory-workers image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/faktory-workers/Dockerfile
          context: cmd/faktory-workers
          tags: quay.io/goss_beta/faktory-workers:${{ github.sha }}
