name: Build and Push Auth Image
on:
  push:
    branches:
      - main
    paths:
    - 'internal/auth/**'
    - 'cmd/auth/**'
    - 'api/proto/auth/**'
    - 'build/docker/auth/**'

jobs:
  push_to_registry:
    name: Push auth-service image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/auth/Dockerfile
          context: .
          tags: quay.io/goss_beta/auth-service:${{ github.sha }}
