name: Build and Push Gateway Image
on:
  push:
    branches:
      - main
    paths:
    - 'internal/gateway/**'
    - 'cmd/gateway/**'
    - 'api/proto/gateway/**'
    - 'build/docker/gateway/**'

jobs:
  push_to_registry:
    name: Push gateway-service image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/gateway/Dockerfile
          context: .
          tags: quay.io/goss_beta/gateway-service:${{ github.sha }}
