name: Build and Push Payment Image
on:
  push:
    branches:
      - main
    paths:
    - 'internal/payment/**'
    - 'cmd/payment/**'
    - 'api/proto/payment/**'
    - 'build/docker/payment/**'

jobs:
  push_to_registry:
    name: Push payment-service image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-image
        with:
          dockerfile: build/docker/payment/Dockerfile
          context: .
          tags: quay.io/goss_beta/payment-service:${{ github.sha }}
