// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/NeptuneG/go-back/pkg/types"
	"github.com/google/uuid"
)

type Artist struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	Description types.NullString `json:"description"`
	Slug        types.NullString `json:"slug"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type LiveEvent struct {
	ID              uuid.UUID        `json:"id"`
	LiveHouseID     uuid.UUID        `json:"live_house_id"`
	Title           string           `json:"title"`
	Url             string           `json:"url"`
	Description     types.NullString `json:"description"`
	PriceInfo       types.NullString `json:"price_info"`
	StageOneOpenAt  types.NullTime   `json:"stage_one_open_at"`
	StageOneStartAt time.Time        `json:"stage_one_start_at"`
	StageTwoOpenAt  types.NullTime   `json:"stage_two_open_at"`
	StageTwoStartAt types.NullTime   `json:"stage_two_start_at"`
	Slug            types.NullString `json:"slug"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
	AvailableSeats  int32            `json:"available_seats"`
}

type LiveHouse struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Address   types.NullString `json:"address"`
	Slug      types.NullString `json:"slug"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

type User struct {
	ID                 uuid.UUID        `json:"id"`
	Email              string           `json:"email"`
	EncryptedPassword  string           `json:"encrypted_password"`
	ResetPasswordToken types.NullString `json:"reset_password_token"`
	CreatedAt          time.Time        `json:"created_at"`
	UpdatedAt          time.Time        `json:"updated_at"`
}

type UserOrder struct {
	ID          uuid.UUID `json:"id"`
	LiveEventID uuid.UUID `json:"live_event_id"`
	UserID      uuid.UUID `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UserPoint struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Points      int32            `json:"points"`
	Description types.NullString `json:"description"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}
