// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Artist struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Slug        sql.NullString `json:"slug"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type LiveEvent struct {
	ID              uuid.UUID      `json:"id"`
	LiveHouseID     uuid.UUID      `json:"liveHouseID"`
	Title           string         `json:"title"`
	Url             string         `json:"url"`
	Description     sql.NullString `json:"description"`
	PriceInfo       sql.NullString `json:"priceInfo"`
	StageOneOpenAt  sql.NullTime   `json:"stageOneOpenAt"`
	StageOneStartAt time.Time      `json:"stageOneStartAt"`
	StageTwoOpenAt  sql.NullTime   `json:"stageTwoOpenAt"`
	StageTwoStartAt sql.NullTime   `json:"stageTwoStartAt"`
	Slug            sql.NullString `json:"slug"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

type LiveHouse struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Slug      sql.NullString `json:"slug"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type User struct {
	ID                 uuid.UUID      `json:"id"`
	Email              string         `json:"email"`
	EncryptedPassword  string         `json:"encryptedPassword"`
	ResetPasswordToken sql.NullString `json:"resetPasswordToken"`
	CreatedAt          time.Time      `json:"createdAt"`
	UpdatedAt          time.Time      `json:"updatedAt"`
}

type UserOrder struct {
	ID          uuid.UUID `json:"id"`
	LiveEventID uuid.UUID `json:"liveEventID"`
	UserID      uuid.UUID `json:"userID"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}
